export enum ActionType {
  SIGN_IN = "SIGN_IN",
  SIGN_OUT = "SIGN_OUT",
  USER_SIGN_UP = "USER_SIGN_UP",
  ADMIN_SIGN_UP = "ADMIN_SIGN_UP",
  USER_EDIT = "USER_EDIT",
  USER_DELETE = "USER_DELETE",
  ADMIN_DELETE = "ADMIN_DELETE",
  ADMIN_EDIT = "ADMIN_EDIT",
  ADD_PROJECT = "ADD_PROJECT",
  ERROR = "ERROR",
}
